version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "sam-kinesisAnalytics"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1q2sopnpmel9w"
s3_prefix = "sam-kinesisAnalytics"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
